-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgU1/7GATZCrdmcrgJ
8zWWCGKB2Kbh7c3HxJlaVSuaiumgCgYIKoZIzj0DAQehRANCAATsu3zTgeNJFwAq
Y+n2ja/DMfYJRwKYrAV9GO5GZr0IN3gv3JW8LaHnWgp/aDIIBVtT8JXylvReKtt1
JB4j1NdA
-----END PRIVATE KEY-----