"""define elder call relationship

Revision ID: 13c367b7e294
Revises: 0cd053353e47
Create Date: 2025-11-23 01:20:15.053963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c367b7e294'
down_revision: Union[str, Sequence[str], None] = '0cd053353e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elders', sa.Column('relation', sa.String(length=255), nullable=False))
    op.drop_column('elders', 'relationship')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elders', sa.Column('relationship', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('elders', 'relation')
    # ### end Alembic commands ###
