"""add_invite_code_to_elder

Revision ID: 354b9925157a
Revises: 5956dfbf598c
Create Date: 2025-11-22 22:52:22.661235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354b9925157a'
down_revision: Union[str, Sequence[str], None] = '5956dfbf598c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elders', sa.Column('invite_code', sa.String(length=6), nullable=False))
    op.create_index(op.f('ix_elders_invite_code'), 'elders', ['invite_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elders_invite_code'), table_name='elders')
    op.drop_column('elders', 'invite_code')
    # ### end Alembic commands ###
