"""initial schema

<<<<<<<< HEAD:alembic/versions/a2115e1b5afc_initial_schema.py
Revision ID: a2115e1b5afc
Revises: 
Create Date: 2025-11-23 19:42:51.999479
========
Revision ID: 2731dbe03d4d
Revises: 
Create Date: 2025-11-24 02:05:32.919461
>>>>>>>> dev:alembic/versions/2731dbe03d4d_initial_schema.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:alembic/versions/a2115e1b5afc_initial_schema.py
revision: str = 'a2115e1b5afc'
========
revision: str = '2731dbe03d4d'
>>>>>>>> dev:alembic/versions/2731dbe03d4d_initial_schema.py
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('elders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
<<<<<<<< HEAD:alembic/versions/a2115e1b5afc_initial_schema.py
========
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
>>>>>>>> dev:alembic/versions/2731dbe03d4d_initial_schema.py
    sa.Column('relation', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('residence_type', sa.String(length=255), nullable=False),
    sa.Column('health_condition', sa.String(length=511), nullable=False),
    sa.Column('begin_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('ask_meal', sa.Boolean(), nullable=False),
    sa.Column('ask_medication', sa.Boolean(), nullable=False),
    sa.Column('ask_emotion', sa.Boolean(), nullable=False),
    sa.Column('ask_special_event', sa.Boolean(), nullable=False),
    sa.Column('additional_info', sa.String(length=511), nullable=True),
    sa.Column('invite_code', sa.String(length=6), nullable=False),
    sa.Column('voip_device_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elders_invite_code'), 'elders', ['invite_code'], unique=False)
    op.create_index(op.f('ix_elders_voip_device_token'), 'elders', ['voip_device_token'], unique=False)
    op.create_table('call_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['elder_id'], ['elders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vapi_call_id', sa.String(length=255), nullable=True),
    sa.Column('elder_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['elder_id'], ['elders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_vapi_call_id'), 'calls', ['vapi_call_id'], unique=True)
    op.create_table('call_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_messages')
    op.drop_index(op.f('ix_calls_vapi_call_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_table('call_schedules')
    op.drop_index(op.f('ix_elders_voip_device_token'), table_name='elders')
    op.drop_index(op.f('ix_elders_invite_code'), table_name='elders')
    op.drop_table('elders')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
