"""add voip_device_token to elder

Revision ID: f61b0f94e168
Revises: 354b9925157a
Create Date: 2025-11-23 00:17:22.340068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61b0f94e168'
down_revision: Union[str, Sequence[str], None] = '354b9925157a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elders', sa.Column('voip_device_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_elders_voip_device_token'), 'elders', ['voip_device_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elders_voip_device_token'), table_name='elders')
    op.drop_column('elders', 'voip_device_token')
    # ### end Alembic commands ###
